server:
  port: 9000

spring:
  spring.main.allow-circular-references: true
  datasource:
    url: jdbc:mysql://mysqlemployee:3306/employee
    password: root
    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

#  application:
#    name: Employee_Service_Test

